### ISSUE TITLE
Linux Headless missing files for loading visual

### ISSUE THREAD

**Issue by troyBORG** [resonite-modding-group/ResoniteModLoader#2]
With the new 2.5.0 build you added a visual bar for load.  But the linux build is missing files like  Assembly-CSharp and UnityEngine.CoreModule that are required for it to load.  Which causes the mod loader to fail to load.

If you add the "hidevisuals" options in the ResoniteModLoader.config it will load up correctly.
So there needs to be some kinda check to see if it is Linux/Headless to tell it to not load the visuals.

**Comment by XDelta** [comment]
Fixed in 2.5.1
