### ISSUE TITLE
Mod loader fails if trying to load multiple plugins

### ISSUE THREAD

**Issue by Nytra** [resonite-modding-group/ResoniteModLoader#3]
I am trying to load two assemblies with Resonite:
- ResoniteModLoader.dll
- Project-Obsidian.dll

However RML is failing when attempting this.

Log file:

[DESKTOP-H976HO2 - 2023.11.28.1365 - 2023-11-30 01_44_11.log](https://github.com/resonite-modding-group/ResoniteModLoader/files/13507381/DESKTOP-H976HO2.-.2023.11.28.1365.-.2023-11-30.01_44_11.log)

**Comment by Nytra** [comment]
This is something that used to work fine in Neos

**Comment by XDelta** [comment]
I've narrowed down where this is occurring, will be working on a fix later tonight.

**Comment by XDelta** [comment]
Fix included in 2.6.0
